// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAgent = "agents"

// Agent mapped from table <agents>
type Agent struct {
	ID   int32  `gorm:"column:id;not null" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName Agent's table name
func (*Agent) TableName() string {
	return TableNameAgent
}
