// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEvent = "events"

// Event mapped from table <events>
type Event struct {
	ID                  int32  `gorm:"column:id;not null" json:"id"`
	Name                string `gorm:"column:name;not null" json:"name"`
	ShortDescription    string `gorm:"column:short_description;not null" json:"shortDescription"`
	ClassificacaoEtaria string `gorm:"column:classificacao_etaria;not null" json:"classificacaoEtaria"`
}

// TableName Event's table name
func (*Event) TableName() string {
	return TableNameEvent
}
