// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProject = "projects"

// Project mapped from table <projects>
type Project struct {
	ID   int32  `gorm:"column:id;not null" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
