// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSpace = "spaces"

// Space mapped from table <spaces>
type Space struct {
	ID   int32  `gorm:"column:id;not null" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName Space's table name
func (*Space) TableName() string {
	return TableNameSpace
}
